### ISSUE TITLE
We need a breakfast recipe!

### ISSUE THREAD

**Issue by AngusMaguir3** [IntroToCode/RecipesCodemates6#1]
## 💬 Discussion topic

I really wish I had a good breakfast recipe.

## ❗ Potential issues

I just want something simple and delicious.

## 👥 People to consult

@unakim 
@Chyi-Shin 

## 📃 Details

Hope we can all come to agreement on a good recipe. Need to know ingredients, servings and steps.

**Comment by Chyi-Shin** [comment]
how about chocolate chip pancakes?

I understand the requirements as Ingredients, Servings, Steps!

**Comment by AngusMaguir3** [comment]
I love chocolate chip pancakes! As long as the recipe is step by step and detailed it shouldn't be too hard for me!

**Comment by AngusMaguir3** [comment]
We've figured out a great breakfast!

**Comment by santip21** [comment]
Went through the recipe and loved it! Great job chefs!!!
