### ISSUE TITLE
Dinner needs a wine pairing!

### ISSUE THREAD

**Issue by Chyi-Shin** [IntroToCode/RecipesCodemates6#10]
## 💬 Discussion topic

To make this dinner more fancy, let's add a wine pairing!

## ❗ Potential issues

I don't like white wine

## 👥 People to consult
@caitrin-hall @AngusMaguir3 @unakim 

## 📃 Details

Text

**Comment by santip21** [comment]
Wine pairing is done and non-alcoholic beverages suggestions as well!
