### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by caitrin-hall** [IntroToCode/RecipesCodemates6#17]
## 💬 Discussion topic

Acceptance criteria

## ❗ Potential issues

Need to make sure we have agreement on this menu that we're going to ship in our next sprint. Does it look delicious, edible, and desirable to all of you? If so we're open for biz!

## 👥 People to consult

@AngusMaguir3 @Chyi-Shin @unakim @santip21 

## 📃 Details

Need everyone to comment and ensure we have acceptance for the recipes we wrote.

**Comment by AngusMaguir3** [comment]
I think these recipes are great! They all look delicious and think our customers will love these!

**Comment by santip21** [comment]
Definitely! I agree with your proposed acceptance criteria, I would also add that the recipes should be allergies free.
Cheers!

**Comment by Chyi-Shin** [comment]
It looks fantastic - thanks for confirming @caitrin-hall

**Comment by unakim** [comment]
For each recipe, we need to include Servings, Time, Ingredients, Equipment, Steps, and Notes to ensure we can accept the meal. Looks good to go 💯

**Comment by santip21** [comment]
Great that we are all on the same page! Closing the issue!
