### ISSUE TITLE
Lunch recipe - Help!

### ISSUE THREAD

**Issue by Chyi-Shin** [IntroToCode/RecipesCodemates6#2]
## 💬 Discussion topic

love me a good lunch recipe!

## ❗ Potential issues

too many cuisines to choose from!

## 👥 People to consult

@caitrin-hall @AngusMaguir3 

## 📃 Details

Help me choose!!

**Comment by unakim** [comment]
What about PB&J sandwich? Such a classic!

I understand that the requirements are to include Servings, Time, Ingredients, Equipment, Steps, and Notes. The acceptance criteria should be a full description of each of the requirements and further agreement on the overall meal selection.
