### ISSUE TITLE
Blank Dinner Recipe

### ISSUE THREAD

**Issue by unakim** [IntroToCode/RecipesCodemates6#3]
## 💬 Discussion topic

Our dinner recipe is missing! Let's create something delicious together so that we can meet as a team once COVID is over to break bread :) 

## ❗ Potential issues

We need to submit a dinner recipe! Any thoughts on what kind of meal we should be cooking up?

## 👥 People to consult

@santip21 @AngusMaguir3 @caitrin-hall @Chyi-Shin 

## 📃 Details

For our recipe, we need to include Servings, Time, Ingredients, Equipment, Steps, and Notes.

**Comment by Chyi-Shin** [comment]
what about spaghetti?

**Comment by santip21** [comment]
Mi piace tantissimo il spaghetti!
I understand the details to fix this issue: Ingredients, cooking time, steps to cook, and the Recipe Notes.

**Comment by AngusMaguir3** [comment]
I don't really like this recipe... Sorry team. Does anyone else think they can spice it up?

**Comment by AngusMaguir3** [comment]
We've figured out a great recipe! Darn I'm hungry
